[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "portscan"
version = "0.8.0"
description = "A lightweight port scanner"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "BSD-3-Clause" }

[project.scripts]
reconlisk = "portscan.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
